apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-api.name" . }}
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "customer-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "customer-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "customer-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:45001
            - name: spring__cloud__config__uri
              value: http://config-service:8888
            - name: eureka__instance__hostName
              value: localhost
            - name: eureka__instance__port
              value:  {{ .Values.service.port | quote }}
            - name: eureka__instance__preferIpAddress
              value: "true"
            - name: eureka__client__serviceurl
              value: http://eureka-service:8761/eureka/
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-linux-secret
                  key: sapassword
            - { name: ConnectionString, value: "{{ printf "Server=mssql-linux;Database=restaurant.Services.Customer;User Id=sa;Password=$(DATABASE_PASSWORD)" }}"}              
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
