apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config-service.name" . }}-config
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
data:
  application.yml: |-
    AppSettings:
      SiteTitle: DotNetFullMasterStack
      CacheDbResults: true
    Logging:
      LogLevel:
        Default: Information
          System: Warning
          Microsoft: Warning
          Steeltoe: Information
    eureka:
      client:
        serviceUrl: http://eureka-service:8761/eureka/
      instance:
        StatusPageUrlPath: /actuator/info
        HealthCheckUrlPath: /actuator/health
    management:
      endpoints:
        actuator:
          exposure:
            include: [ "*" ]
