version: '3.4'

services:
  customer-api-test:
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/customer-api-test-results.xml
        - --collect:"XPlat Code Coverage"
        - /p:CollectCoverage=true 
        - /p:CoverletOutputFormat=cobertura
        - /p:CoverletOutput=/tests/