version: '3.4'

services:
  sqlserver:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  customer-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Customer;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://configserver:8888
      - eureka__instance__hostName=customer-api
      - eureka__instance__port=80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  kitchen-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Kitchen;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://configserver:8888
      - eureka__instance__hostName=kitchen-api
      - eureka__instance__port=80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Ordering;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://configserver:8888
      - eureka__instance__hostName=ordering-api
      - eureka__instance__port=80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  restaurant-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Restaurant;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://configserver:8888
      - eureka__instance__hostName=restaurant-api
      - eureka__instance__port=80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro