version: '3.4'

services:
  config-service:
    #image: "steeltoeoss/config-server:latest"
    image: ${REGISTRY:-dotnetfullmasterstack}/config-service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./SpringCloud/config-service/
      dockerfile: Dockerfile   
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./config-server
        target: /config
    ports:
      - "8888:8888"
  eureka-service:
    image: ${REGISTRY:-dotnetfullmasterstack}/eureka-service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./SpringCloud/eureka-service/
      dockerfile: Dockerfile    
    ports:
      - "8761:8761"
  admin-service:
    image: ${REGISTRY:-dotnetfullmasterstack}/admin-service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./SpringCloud/admin-service/
      dockerfile: Dockerfile  
    environment:
        - EUREKA_SERVICE_URL=http://eureka-service:8761
    ports:
       - "8889:8889"
    depends_on:
       - eureka-service
  gateway-service:
     environment:
       - EUREKA_SERVICE_URL=http://eureka-service:8761
     image: ${REGISTRY:-dotnetfullmasterstack}/gateway-service:${PLATFORM:-linux}-${TAG:-latest}
     build:
      context: ./SpringCloud/gateway-service/
      dockerfile: Dockerfile  
     ports:
       - "8181:8181"
     depends_on:
       - eureka-service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest

  customer-api:
    image: ${REGISTRY:-dotnetfullmasterstack}/customer.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Customer/Customer.API/Dockerfile
    depends_on:
      - sqlserver
  kitchen-api:
    image: ${REGISTRY:-dotnetfullmasterstack}/kitchen.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Kitchen/Kitchen.API/Dockerfile
    depends_on:
      - sqlserver
  ordering-api:
    image: ${REGISTRY:-dotnetfullmasterstack}/ordering.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sqlserver
  restaurant-api:
    image: ${REGISTRY:-dotnetfullmasterstack}/restaurant.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Restaurant/Restaurant.API/Dockerfile   
    depends_on:
      - sqlserver
      
