version: '3.4'

services:
  sqlserver:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  customer-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:45000;http://+:45001
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Customer;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://config-service:8888
      - eureka__instance__hostName=localhost
      - eureka__instance__port=45001
      - eureka__instance__preferIpAddress=true
      - eureka__client__serviceurl=http://eureka-service:8761/eureka/
    ports:
      - "45001:45001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  kitchen-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:46000;http://+:46001
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Kitchen;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://config-service:8888
      - eureka__instance__hostName=localhost
      - eureka__instance__port=46001
      - eureka__instance__preferIpAddress=true
      - eureka__client__serviceurl=http://eureka-service:8761/eureka/
    ports:
      - "46001:46001"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:47000;http://+:47001
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Ordering;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://config-service:8888
      - eureka__instance__hostName=localhost
      - eureka__instance__port=47001
      - eureka__instance__preferIpAddress=true
      - eureka__client__serviceurl=http://eureka-service:8761/eureka/
    ports:
      - "47001:47001"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  restaurant-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:48000;http://+:48001
      - ConnectionString=${RESTAURANT_DATABASE_SERVER:-Server=sqlserver;Database=restaurant.Services.Restaurant;User Id=sa;Password=Pass@word} 
      - spring__cloud__config__uri=http://config-service:8888
      - eureka__instance__hostName=localhost
      - eureka__instance__port=48001
      - eureka__instance__preferIpAddress=true
      - eureka__client__serviceurl=http://eureka-service:8761/eureka/
    ports:
      - "48001:48001"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro